MODEL (
    name main.raw_risk_data,
    kind SEED (
        path '../seeds/seed_data.csv'
    ),
    columns (
        Transaction_ID INTEGER,
        event_date TEXT,
        Scenario TEXT,
        Asset_Class TEXT,
        Sub_Asset_Class TEXT,
        Variable_X DOUBLE,
        Variable_Y DOUBLE,
        Underlying_Asset_Price DOUBLE,
        Option_Strike_Price DOUBLE,
        Risk_Free_Rate DOUBLE,
        Time_To_Maturity DOUBLE,
        Asset_Volatility DOUBLE,
        Return_Asset1 DOUBLE,
        Return_Asset2 DOUBLE,
        Return_Asset3 DOUBLE,
        Weight_Asset1 DOUBLE,
        Weight_Asset2 DOUBLE,
        Weight_Asset3 DOUBLE,
        Portfolio_Return DOUBLE,
        Cash_Flow_Period1 DOUBLE,
        Cash_Flow_Period2 DOUBLE,
        Cash_Flow_Period3 DOUBLE,
        Bond_Yield DOUBLE,
        CashFlow_TimePeriod1 DOUBLE,
        CashFlow_TimePeriod2 DOUBLE,
        CashFlow_TimePeriod3 DOUBLE,
        Probability_Default DOUBLE,
        Loss_Given_Default DOUBLE,
        Exposure_At_Default DOUBLE,
        Bid_Price DOUBLE,
        Ask_Price DOUBLE,
        Base_Asset_Value DOUBLE,
        Stressed_Asset_Value DOUBLE,
        Stress_Exposure DOUBLE,
        Gross_Income DOUBLE,
        Asset_Risk_Weight DOUBLE,
        Additional_Liquidity_Risk DOUBLE,
        Time_Series_Lag_Value DOUBLE,
        Current_Time_Series_Value DOUBLE
    ),
    grain (Transaction_ID, event_date)
);
