MODEL (
  name main.staging_risk_data,
  dialect duckdb
);

SELECT
  Transaction_ID,
  STRPTIME(event_date, '%d/%m/%Y') AS event_date,
  Scenario,
  Asset_Class,
  Sub_Asset_Class,
  Variable_X,
  Variable_Y,
  Underlying_Asset_Price,
  Option_Strike_Price,
  Risk_Free_Rate,
  Time_To_Maturity,
  Asset_Volatility,
  Return_Asset1,
  Return_Asset2,
  Return_Asset3,
  Weight_Asset1,
  Weight_Asset2,
  Weight_Asset3,
  Portfolio_Return,
  Cash_Flow_Period1,
  Cash_Flow_Period2,
  Cash_Flow_Period3,
  Bond_Yield,
  CashFlow_TimePeriod1,
  CashFlow_TimePeriod2,
  CashFlow_TimePeriod3,
  Probability_Default,
  Loss_Given_Default,
  Exposure_At_Default,
  Bid_Price,
  Ask_Price,
  Base_Asset_Value,
  Stressed_Asset_Value,
  Stress_Exposure,
  Gross_Income,
  Asset_Risk_Weight,
  Additional_Liquidity_Risk,
  Time_Series_Lag_Value,
  Current_Time_Series_Value
FROM main.raw_risk_data;
